# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: health_childcare_dev
  pool: 5
  username: jean
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: health_childcare_test
  pool: 5
  username: jean
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
