#SurveyGizmo Key
SURVEYGIZMO_API_TOKEN: 22dcd58622cda2f5c87b65b2abe70420bf75920b7c4b0b2d9d
SURVEYGIZMO_API_TOKEN_SECRET: A954H8aviF0do  

#SendingBlue Key
SENDINGBLUE_URL: https://api.sendinblue.com/v2.0
SENDINGBLUE_TOKEN: k4ptKwAELb0R6xB5

#Daycare Manager
SITE_MANAGER_EMAIL: infectionpreventivecare@healthierandsaferchildcare.org
SITE_MANAGER_NAME: HealthCare Manager
BASE_URL: http://healthierandsaferchildcare.org

# Predefined Subject Key

SURVEY_TEMPLATE_SUBJECT: SURVEY_TEMPLATE_SUBJECT
SURVEY_TEMPLATE_SUBJECT_WORKER: SURVEY_TEMPLATE_SUBJECT_WORKER
SURVEY_TEMPLATE_SUBJECT_PARENTEE: SURVEY_TEMPLATE_SUBJECT_WORKER_SUBJECT
SURVEY_TEMPLATE_SUBJECT_MANAGER: SURVEY_TEMPLATE_SUBJECT_MANAGER

# Email Verification Email Key
EMAIL_VERIFICATION_SUBJECT: EMAIL_VERIFICATION_SUBJECT
EMAIL_VERIFICATION_SUBJECT_DEPOSIT: EMAIL_VERIFICATION_SUBJECT_DEPOSIT
EMAIL_VERIFICATION_SUBJECT_REGISTER: EMAIL_VERIFICATION_SUBJECT_REGISTER

# Acuity Scheduing Key
ACUITY_SCHEDULE_URL: https://acuityscheduling.com/api/v1/
ACUITY_SCHEDULE_USER: "13092943"
ACUITY_SCHEDULE_PASSWORD: b1a2264ff0dd67fb06c5fe2788c5802b