#SurveyGizmo Key
SURVEYGIZMO_API_TOKEN: 22dcd58622cda2f5c87b65b2abe70420bf75920b7c4b0b2d9d
SURVEYGIZMO_API_TOKEN_SECRET: A954H8aviF0do  

#SendingBlue Key
SENDINGBLUE_URL: https://api.sendinblue.com/v2.0
SENDINGBLUE_TOKEN: k4ptKwAELb0R6xB5

# Predefined Subject Key

SURVEY_TEMPLATE_SUBJECT: SURVEY_INVITATION_TEMPLATE_SUBJECT
SURVEY_TEMPLATE_SUBJECT_WORKER: SURVEY_INVITATION_WORKER_SUBJECT
SURVEY_TEMPLATE_SUBJECT_PARENTEE: SURVEY_INVITATION_WORKER_SUBJECT
SURVEY_TEMPLATE_SUBJECT_MANAGER: SURVEY_INVITATION_WORKER_SUBJECT